### ISSUE TITLE
data wranging - rjava install issue

### ISSUE THREAD

**Issue by hspopal** [TU-Coding-Outreach-Group/cog_summer_workshops_2022#5]
User was unable to install rjava. Something about couldn't find java home? They were using a PC.

**Comment by Wjpmitchell3** [comment]
There's not really anything we can do about this directly. It seems to stem from users have an incongruent version of Java (i.e., 32-bit). Both Java and R should be 64-bit for this to work. We already had a notice about this, but I made the error and solution more explicit and included links to more resources on the issue.
