### ISSUE TITLE
data wrangling - piping breakdown

### ISSUE THREAD

**Issue by hspopal** [TU-Coding-Outreach-Group/cog_summer_workshops_2022#6]
I think we should explain piping a bit more. I liked Billy's example where he wrote a simple nested function and then showed how it would be down with piping. Kind of like exercise one, but maybe it will be helpful to include a simple one in the beginning with simple math (e.g. take the square root, then plot in a histogram).

**Comment by Wjpmitchell3** [comment]
Great suggestion Haroon. I adding a little bit of a background about pipes and used a demonstration where I take a random sample, get the mean of it, log it, and then round it, and I showed three progressively better ways of approaching this problem, ultimately culminating in piping, which I think demonstrates the utility.
